<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pricing.Application\Pricing.Application.csproj" />
    <ProjectReference Include="..\Pricing.Domain\Pricing.Domain.csproj" />
  </ItemGroup>
</Project>
