<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pricing.Application\Pricing.Application.csproj" />
    <ProjectReference Include="..\..\src\Pricing.Domain\Pricing.Domain.csproj" />
  </ItemGroup>
</Project>
